"""HTTP routes exposed by the assistant module.

Mounted at ``/assist`` by the app. The router is deliberately thin:
it validates, dispatches to the service, and streams the result back.
No business logic lives here.
"""
# NOTE: deliberately *no* ``from __future__ import annotations`` here —
# FastAPI needs the response_model class objects to be eagerly
# resolvable (not ForwardRefs) so the serializer can build at startup.
# Same call as src/api/routers/auth.py.

from collections.abc import AsyncGenerator
import os
from typing import Annotated

from dishka.integrations.fastapi import FromDishka, inject
from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from src.api.auth import get_current_user
from src.api.openapi_responses import RESOURCE_RESPONSES
from src.assistant.credential_repository import CredentialRepository, McpTokenRepository
from src.assistant import local_models
from src.assistant.model_prefs import ModelPreferenceRepository
from src.assistant.credentials import (
    SUPPORTED_PROVIDERS,
    CredentialEncryptionUnavailable,
    validate_provider,
)
from src.assistant.service import AssistantService, ChatRequest
from src.domain.user import User


router = APIRouter(prefix="/assist", tags=["assist"], responses=RESOURCE_RESPONSES)


# ── Request / response models ─────────────────────────────────


class AssistChatBody(BaseModel):
    """Request body for POST /assist/chat/stream.

    ``conversation_key`` is an opaque caller-chosen identifier. For the
    report editor it's ``report:<uuid>``. The assistant doesn't look
    inside it.

    ``context_block`` is a pre-rendered string the caller wants to put
    in the assistant's field of view for this turn. The assistant will
    truncate it to fit its own budget before sending to the LLM.
    """

    message: str = Field(..., min_length=1)
    conversation_key: str = Field(..., min_length=1)
    context_block: str = ""
    nav: dict | None = Field(
        None,
        description=(
            "Where the user is and which pages exist, generated by the "
            "frontend from its own router. Absent means the assistant "
            "simply will not navigate this turn."
        ),
    )


class UsageResponse(BaseModel):
    """Rolling-window token totals for the current user."""
    tokens_1h: int
    tokens_24h: int
    tokens_7d: int


class DailyUsagePoint(BaseModel):
    """A single day's token totals in a usage-history response."""
    date: str
    tokens_in: int
    tokens_out: int


class UsageHistoryResponse(BaseModel):
    """Per-day token consumption over the requested window."""
    days: int
    points: list[DailyUsagePoint]


class HistoryMessage(BaseModel):
    """A single persisted assistant/user message in a conversation history view."""
    role: str
    content: str
    created_at: str
    tokens_in: int | None = None
    tokens_out: int | None = None


# ── Endpoints ──────────────────────────────────────────────────


# Return annotation is omitted deliberately: FastAPI would otherwise
# try to build a Pydantic response model for ``StreamingResponse``
# (not a Pydantic type) and crash /openapi.json with a 500.
# ``response_class=`` tells FastAPI this is a streaming endpoint
# without involving schema generation.
@router.post("/chat/stream", response_class=StreamingResponse)
@inject
async def chat_stream(
    body: AssistChatBody,
    *,
    service: FromDishka[AssistantService],
    credentials: FromDishka[CredentialRepository],
    model_prefs: FromDishka[ModelPreferenceRepository],
    user: Annotated[User, Depends(get_current_user)],
):
    """Stream an assistant reply via SSE."""
    # Resolved here, per request, and handed to the turn. The proxy client
    # is an APP-scoped singleton shared by every user, so the key must
    # travel with the request rather than live on the client.
    try:
        credential = await credentials.get_secret_for_turn(user.id)
    except CredentialEncryptionUnavailable:
        # Misconfigured master key: fall back to the platform key if there
        # still is one, rather than taking the assistant down entirely.
        credential = None

    # Read per request for the same reason as the credential: the proxy
    # client is an APP-scoped singleton, so anything user-specific has to
    # travel with the turn rather than live on it.
    local_model_id = await model_prefs.get(user.id)

    req = ChatRequest(
        user_id=user.id,
        conversation_key=body.conversation_key,
        message=body.message,
        context_block=body.context_block,
        nav=body.nav,
        credential=credential,
        local_model_id=local_model_id,
    )

    async def generator() -> AsyncGenerator[str, None]:
        async for line in service.turn(req):
            yield line
        yield "event: done\ndata: {}\n\n"

    return StreamingResponse(
        generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@router.get("/usage")
@inject
async def usage(
    *,
    service: FromDishka[AssistantService],
    user: Annotated[User, Depends(get_current_user)],
) -> UsageResponse:
    """Return the current user's token consumption over rolling windows."""
    snapshot = await service.usage_for_user(user.id)
    return UsageResponse(
        tokens_1h=snapshot.tokens_1h,
        tokens_24h=snapshot.tokens_24h,
        tokens_7d=snapshot.tokens_7d,
    )


@router.get("/usage-history")
@inject
async def usage_history(
    *,
    days: Annotated[int, Query(ge=1, le=365)] = 30,
    service: FromDishka[AssistantService],
    user: Annotated[User, Depends(get_current_user)],
) -> UsageHistoryResponse:
    """Return per-day token totals for the current user over the last N days."""
    rows = await service.usage_history_for_user(user.id, days=days)
    return UsageHistoryResponse(
        days=days,
        points=[
            DailyUsagePoint(
                date=r.day.isoformat(),
                tokens_in=r.tokens_in,
                tokens_out=r.tokens_out,
            )
            for r in rows
        ],
    )


@router.delete("/conversations")
@inject
async def delete_all_conversations(
    *,
    user: Annotated[User, Depends(get_current_user)],
    service: FromDishka[AssistantService],
) -> dict:
    """Delete all conversation history for the current user."""
    count = await service.delete_user_conversations(user.id)
    return {"deleted": count}


@router.get("/conversations/{conversation_key:path}")
@inject
async def get_conversation(
    conversation_key: str,
    *,
    service: FromDishka[AssistantService],
    user: Annotated[User, Depends(get_current_user)],
) -> dict:
    """Return the full stored history for a conversation key, scoped to the user."""
    # AssistantService's public surface is turn-based (chat / usage);
    # there's no dedicated "fetch a stored conversation" verb because
    # the only consumer is this introspection endpoint. Reach through
    # to the repo handle.
    # pylint: disable=protected-access
    conv = await service._repo.find_or_create_conversation(user.id, conversation_key)
    messages = await service._repo.list_messages(conv.id)
    # pylint: enable=protected-access
    return {
        "conversation_key": conversation_key,
        "messages": [
            {
                "role": m.role,
                "content": m.content,
                "created_at": m.created_at.isoformat(),
                "tokens_in": m.tokens_in,
                "tokens_out": m.tokens_out,
            }
            for m in messages
        ],
    }


# ── Provider credentials ──────────────────────────────────────
#
# Write-only, the way a password is: a key goes in and never comes back
# out through the API. Callers get a fingerprint so they can tell WHICH
# key is stored without being shown any part of it.


class ProviderCredentialIn(BaseModel):
    provider: str = Field(..., description=f"One of: {', '.join(SUPPORTED_PROVIDERS)}")
    api_key: str = Field(..., min_length=8, description="Your own provider API key.")
    model: str | None = Field(
        None, description="Optional model override, e.g. 'claude-sonnet-4-5'.",
    )


@router.put(
    "/credentials",
    status_code=200,
    responses={
        422: {"description": "Unsupported provider."},
        503: {"description": "Credential encryption is not configured."},
    },
)
@inject
async def put_credential(
    body: ProviderCredentialIn,
    repo: FromDishka[CredentialRepository],
    user: Annotated[User, Depends(get_current_user)],
) -> dict:
    """Store or replace the caller's key for one provider."""
    try:
        provider = validate_provider(body.provider)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    try:
        summary = await repo.upsert(
            user_id=user.id, provider=provider,
            secret=body.api_key.strip(), model=(body.model or None),
        )
    except CredentialEncryptionUnavailable as exc:
        # Never store a secret we cannot protect; 503 because this is our
        # misconfiguration, not the caller's mistake.
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    return summary.as_dict()


@router.get("/models")
@inject
async def list_models(
    *,
    model_prefs: FromDishka[ModelPreferenceRepository],
    user: Annotated[User, Depends(get_current_user)],
):
    """The built-in models on offer, and which one this user picked."""
    return {
        "models": local_models.as_dicts(),
        "selected": await model_prefs.get(user.id),
    }


class ModelChoiceBody(BaseModel):
    """A curated id from local_models, not a model name."""

    model_id: str = Field(..., max_length=64)


@router.put(
    "/models",
    responses={422: {"description": "Unknown model id."}},
)
@inject
async def choose_model(
    body: ModelChoiceBody,
    *,
    model_prefs: FromDishka[ModelPreferenceRepository],
    user: Annotated[User, Depends(get_current_user)],
):
    """Pick a built-in model.

    Rejects anything not on the list rather than storing it: a saved id we
    do not honour would fall back at every turn and look like the setting
    had been ignored.
    """
    try:
        selected = await model_prefs.set(user.id, body.model_id)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    return {"selected": selected}


@router.get("/credentials")
@inject
async def list_credentials(
    repo: FromDishka[CredentialRepository],
    user: Annotated[User, Depends(get_current_user)],
) -> dict:
    """Which providers the caller has configured. Never the keys."""
    return {
        "supported": list(SUPPORTED_PROVIDERS),
        # What the user gets with no key of their own. Reported by the
        # server rather than hardcoded in the frontend so swapping the
        # hosted weights does not need a web release. Null when no local
        # server is configured, which is the frontend's signal to go back
        # to saying a key is required.
        "builtin": (
            {"model": os.environ.get("LOCAL_LLM_MODEL", "qwen3-4b")}
            if os.environ.get("LOCAL_LLM_URL")
            else None
        ),
        "credentials": [c.as_dict() for c in await repo.list_for_user(user.id)],
    }


@router.delete(
    "/credentials/{provider}",
    status_code=204,
    responses={
        404: {"description": "No credential stored for that provider."},
        422: {"description": "Unsupported provider."},
    },
)
@inject
async def delete_credential(
    provider: str,
    repo: FromDishka[CredentialRepository],
    user: Annotated[User, Depends(get_current_user)],
) -> None:
    """Remove a stored key. Deletion has to actually delete."""
    try:
        provider = validate_provider(provider)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    if not await repo.delete(user.id, provider):
        raise HTTPException(status_code=404, detail="No credential for that provider")


# ── MCP access tokens ─────────────────────────────────────────
#
# What a user pastes into their own LLM client so it can reach Fontem's
# tools. Shown once at creation and never again: a token that can be
# re-read is a token an attacker can re-read.


class McpTokenIn(BaseModel):
    label: str = Field("", max_length=80,
                       description="Which client this is for, e.g. 'Claude Desktop'.")


@router.post("/mcp-tokens", status_code=201)
@inject
async def create_mcp_token(
    body: McpTokenIn,
    repo: FromDishka[McpTokenRepository],
    user: Annotated[User, Depends(get_current_user)],
) -> dict:
    """Mint a token. The plaintext is in this response and nowhere else."""
    plaintext, summary = await repo.create(user.id, body.label)
    return {**summary.as_dict(), "token": plaintext}


@router.get("/mcp-tokens")
@inject
async def list_mcp_tokens(
    repo: FromDishka[McpTokenRepository],
    user: Annotated[User, Depends(get_current_user)],
) -> dict:
    """Which clients are connected. Never the tokens themselves."""
    return {"tokens": [t.as_dict() for t in await repo.list_for_user(user.id)]}


@router.delete(
    "/mcp-tokens/{token_id}",
    status_code=204,
    responses={404: {"description": "No such token."}},
)
@inject
async def revoke_mcp_token(
    token_id: str,
    repo: FromDishka[McpTokenRepository],
    user: Annotated[User, Depends(get_current_user)],
) -> None:
    """Disconnect a client."""
    if not await repo.revoke(user.id, token_id):
        raise HTTPException(status_code=404, detail="No such token")


@router.post(
    "/mcp-tokens/verify",
    include_in_schema=False,
    responses={401: {"description": "Invalid or revoked token."}},
)
@inject
async def verify_mcp_token(
    body: dict,
    repo: FromDishka[McpTokenRepository],
) -> dict:
    """Internal: resolve a token to a user for the MCP server.

    Not in the public schema and not reachable from outside the cluster.
    The MCP server calls this rather than re-implementing verification —
    a second verifier is a second place for the rules to drift.
    """
    user_id = await repo.verify((body or {}).get("token", ""))
    if not user_id:
        raise HTTPException(status_code=401, detail="Invalid token")
    return {"user_id": user_id}
