"""HTTP routes exposed by the assistant module.

Mounted at ``/assist`` by the app. The router is deliberately thin:
it validates, dispatches to the service, and streams the result back.
No business logic lives here.
"""
# NOTE: deliberately *no* ``from __future__ import annotations`` here —
# FastAPI needs the response_model class objects to be eagerly
# resolvable (not ForwardRefs) so the serializer can build at startup.
# Same call as src/api/routers/auth.py.

from collections.abc import AsyncGenerator
from datetime import datetime
import os
from typing import Annotated
from uuid import uuid4

from dishka.integrations.fastapi import FromDishka, inject
from fastapi import APIRouter, Depends, HTTPException, Query, Request
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, ConfigDict, Field

from src.api.auth import get_current_user, get_optional_user
from src.api.rate_limit import anonymous_assist_allowed
from src.api.openapi_responses import RESOURCE_RESPONSES, UuidPath
from src.services.exceptions import NotFound
from src.assistant.credential_repository import CredentialRepository, McpTokenRepository
from src.assistant import local_models
from src.assistant.model_prefs import ModelPreferenceRepository
from src.assistant.credentials import (
    SUPPORTED_PROVIDERS,
    CredentialEncryptionUnavailable,
    validate_provider,
)
from src.assistant.service import (
    ANONYMOUS_MAX_PROMPT_CHARS,
    AssistantService,
    ChatRequest,
)
from src.domain.user import User


router = APIRouter(prefix="/assist", tags=["assist"], responses=RESOURCE_RESPONSES)


# ── Request / response models ─────────────────────────────────


class AssistChatBody(BaseModel):
    """Request body for POST /assist/chat/stream.

    ``conversation_key`` is an opaque caller-chosen identifier. For the
    report editor it's ``report:<uuid>``. The assistant doesn't look
    inside it.

    ``context_block`` is a pre-rendered string the caller wants to put
    in the assistant's field of view for this turn. The assistant will
    truncate it to fit its own budget before sending to the LLM.
    """

    message: str = Field(..., min_length=1)
    conversation_key: str = Field(..., min_length=1)
    context_block: str = ""
    has_editor: bool | None = Field(
        None,
        description=(
            "Whether the caller has an editing surface to propose into. "
            "The client knows this — it holds the report id and the editor "
            "state, and needs both to apply a proposal. None means an older "
            "client that does not send it, and the server falls back to "
            "inferring it from context_block."
        ),
    )
    nav: dict | None = Field(
        None,
        description=(
            "Where the user is and which pages exist, generated by the "
            "frontend from its own router. Absent means the assistant "
            "simply will not navigate this turn."
        ),
    )


class UsageResponse(BaseModel):
    """Rolling-window token totals for the current user."""
    tokens_1h: int
    tokens_24h: int
    tokens_7d: int


class DailyUsagePoint(BaseModel):
    """A single day's token totals in a usage-history response."""
    date: str
    tokens_in: int
    tokens_out: int


class UsageHistoryResponse(BaseModel):
    """Per-day token consumption over the requested window."""
    days: int
    points: list[DailyUsagePoint]


class HistoryMessage(BaseModel):
    """A single persisted assistant/user message in a conversation history view."""
    role: str
    content: str
    created_at: str
    tokens_in: int | None = None
    tokens_out: int | None = None


# ── Contract response models ───────────────────────────────────
#
# extra="allow" throughout: handlers enrich these payloads and the
# enrichments must stay free to evolve. What is DECLARED is what API
# consumers may rely on — and what the consumer pacts are validated
# against. Before these existed the whole assistant surface returned a
# bare ``dict``, i.e. formally promised nothing at all.


class AssistMessage(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: str
    role: str
    content: str
    created_at: str
    model: str | None = None
    tokens_in: int | None = None
    tokens_out: int | None = None
    extras: dict = {}


class ConversationSummary(BaseModel):
    model_config = ConfigDict(extra="allow")

    conversation_key: str
    title: str
    updated_at: str
    message_count: int | None = None
    last_snippet: str | None = None


class ConversationListResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    conversations: list[ConversationSummary]


class ConversationResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    conversation_key: str
    messages: list[AssistMessage]


class ConversationPageResponse(ConversationResponse):
    """A page of history, oldest-first, with a cursor flag."""

    has_more: bool


class AssistantModelInfo(BaseModel):
    """One offerable model, as local_models.as_dicts() emits it."""

    model_config = ConfigDict(extra="allow")

    id: str
    label: str
    tokens_per_second: float | int | None = None
    context_tokens: int | None = None
    note: str | None = None
    hosted: bool | None = None


class ModelListResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    models: list[AssistantModelInfo]
    selected: str | None = None
    active: bool | None = None


class ModelChoiceResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    selected: str | None = None


# ── Endpoints ──────────────────────────────────────────────────


# Return annotation is omitted deliberately: FastAPI would otherwise
# try to build a Pydantic response model for ``StreamingResponse``
# (not a Pydantic type) and crash /openapi.json with a 500.
# ``response_class=`` tells FastAPI this is a streaming endpoint
# without involving schema generation.
@router.post(
    "/chat/stream",
    response_class=StreamingResponse,
    # Documented because the handler raises them: an SSE endpoint's error
    # cases are invisible in the schema otherwise, and a client that only
    # reads /openapi.json has no way to learn a turn can be refused.
    responses={
        # Declared so the schema states what this endpoint actually
        # produces; without it a spec-driven client (and the pact
        # cross-validation) sees an endpoint with no content type.
        200: {
            "description": "Server-sent event stream of the assistant turn.",
            "content": {"text/event-stream": {}},
        },
        422: {"description": "The prompt exceeds the anonymous character cap."},
        429: {"description": "The anonymous per-IP allowance for this window is spent."},
    },
)
@inject
# One more argument than pylint's default since `request` joined for the
# rate-limit key. Same call as the auth handlers, which take it for the same
# reason: the client address is only knowable from the request.
# pylint: disable-next=too-many-arguments
async def chat_stream(
    request: Request,
    body: AssistChatBody,
    *,
    service: FromDishka[AssistantService],
    credentials: FromDishka[CredentialRepository],
    model_prefs: FromDishka[ModelPreferenceRepository],
    user: Annotated[User | None, Depends(get_optional_user)],
):
    """Stream an assistant reply via SSE.

    Open to signed-out visitors, who get a reduced assistant: the smallest
    model, `navigate` as its only tool, and nothing persisted. The service
    decides all of that from ``user_id is None`` — the shape of a reduced
    turn is a property of the turn, not of this transport. What belongs here
    is only what the request itself knows: whether there is a user at all,
    and which address is asking.
    """
    if user is None:
        # Checked before the rate limit, so an over-long message costs the
        # caller nothing: being told the rule and being charged for breaking
        # it at the same time is a bad way to meet a limit.
        if len(body.message) > ANONYMOUS_MAX_PROMPT_CHARS:
            raise HTTPException(
                status_code=422,
                detail=(
                    f"Message too long for a signed-out visitor "
                    f"({len(body.message)} characters; the limit is "
                    f"{ANONYMOUS_MAX_PROMPT_CHARS}). Sign in to ask longer "
                    f"questions."
                ),
            )
        # Per IP, and only on this branch — signed-in callers are accounted
        # for by account elsewhere and must not share a bucket with the
        # internet at large.
        if not anonymous_assist_allowed(request):
            raise HTTPException(
                status_code=429,
                detail=(
                    "Too many assistant requests from this address. Sign in "
                    "to continue, or try again later."
                ),
            )
        req = ChatRequest(
            user_id=None,
            conversation_key=body.conversation_key,
            message=body.message,
            context_block=body.context_block,
            # Deliberately not taken from the body: an anonymous turn has no
            # editing surface and no stored model preference, and honouring
            # either from an unauthenticated request would let the caller
            # choose the model that answers it.
            has_editor=False,
            nav=body.nav,
        )
    else:
        # Resolved here, per request, and handed to the turn. The proxy client
        # is an APP-scoped singleton shared by every user, so the key must
        # travel with the request rather than live on the client.
        try:
            credential = await credentials.get_secret_for_turn(user.id)
        except CredentialEncryptionUnavailable:
            # Misconfigured master key: fall back to the platform key if there
            # still is one, rather than taking the assistant down entirely.
            credential = None

        # Read per request for the same reason as the credential: the proxy
        # client is an APP-scoped singleton, so anything user-specific has to
        # travel with the turn rather than live on it.
        local_model_id = await model_prefs.get(user.id)

        req = ChatRequest(
            user_id=user.id,
            conversation_key=body.conversation_key,
            message=body.message,
            context_block=body.context_block,
            has_editor=body.has_editor,
            nav=body.nav,
            credential=credential,
            local_model_id=local_model_id,
        )

    async def generator() -> AsyncGenerator[str, None]:
        async for line in service.turn(req):
            yield line
        yield "event: done\ndata: {}\n\n"

    return StreamingResponse(
        generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@router.get("/usage")
@inject
async def usage(
    *,
    service: FromDishka[AssistantService],
    user: Annotated[User, Depends(get_current_user)],
) -> UsageResponse:
    """Return the current user's token consumption over rolling windows."""
    snapshot = await service.usage_for_user(user.id)
    return UsageResponse(
        tokens_1h=snapshot.tokens_1h,
        tokens_24h=snapshot.tokens_24h,
        tokens_7d=snapshot.tokens_7d,
    )


@router.get("/usage-history")
@inject
async def usage_history(
    *,
    days: Annotated[int, Query(ge=1, le=365)] = 30,
    service: FromDishka[AssistantService],
    user: Annotated[User, Depends(get_current_user)],
) -> UsageHistoryResponse:
    """Return per-day token totals for the current user over the last N days."""
    rows = await service.usage_history_for_user(user.id, days=days)
    return UsageHistoryResponse(
        days=days,
        points=[
            DailyUsagePoint(
                date=r.day.isoformat(),
                tokens_in=r.tokens_in,
                tokens_out=r.tokens_out,
            )
            for r in rows
        ],
    )


@router.delete("/conversations")
@inject
async def delete_all_conversations(
    *,
    user: Annotated[User, Depends(get_current_user)],
    service: FromDishka[AssistantService],
) -> dict:
    """Delete all conversation history for the current user."""
    count = await service.delete_user_conversations(user.id)
    return {"deleted": count}


@router.get("/provenance/{message_id}")
@inject
async def get_provenance(
    message_id: UuidPath,
    *,
    service: FromDishka[AssistantService],
    user: Annotated[User, Depends(get_current_user)],
):
    """What led the agent to do something: the prompt, the tool calls, the answer.

    An activity entry written by the assistant names the tool call that
    caused it. This turns that id back into the exchange it came from, so a
    user can read what they asked and what the agent did about it.

    404 for both "no such message" and "not yours" — telling a stranger which
    ids exist is the whole of what an enumeration attack needs.
    """
    turn = await service.turn_for_message(user.id, message_id)
    if turn is None:
        raise NotFound("No such tool call")
    return turn


# NOTE: the paged route is declared BEFORE the transcript route below.
# `{conversation_key:path}` is greedy — it matches "chat:abc/messages" whole —
# so with the other order the paged endpoint is simply unreachable and every
# request lands on the transcript handler. An isolation test caught it by
# asking for a field the transcript response does not carry; nothing else did,
# because the unit tests exercised the repository rather than the route.
#: How many messages one page carries.
#:
#: The panel renders the newest page on open and pulls older ones as the
#: reader scrolls up, so this is "enough to fill a tall panel and a bit
#: more", not "enough to hold a conversation".
DEFAULT_PAGE_SIZE = 30

#: A caller can ask for more, but not for the whole transcript by setting
#: limit=100000 — that is the behaviour this endpoint exists to replace.
MAX_PAGE_SIZE = 100


def _encode_cursor(msg: dict) -> str:
    """Opaque cursor for one message row: its (created_at, id) key."""
    return f"{msg['created_at']}|{msg['id']}"


def _decode_cursor(raw: str) -> tuple[datetime, str] | None:
    """Parse a cursor, or None if it is unusable.

    A malformed cursor returns the newest page rather than a 422. It is an
    opaque token the client got from us; when it is wrong the useful answer
    is the start of the list, not an error the UI has no way to act on.
    """
    if not raw:
        return None
    stamp, _, msg_id = raw.partition("|")
    if not stamp or not msg_id:
        return None
    try:
        parsed = datetime.fromisoformat(stamp)
    except ValueError:
        return None
    return parsed, msg_id


@router.get("/conversations/{conversation_key:path}/messages",
            response_model=ConversationPageResponse)
@inject
async def page_conversation_messages(
    conversation_key: str,
    *,
    service: FromDishka[AssistantService],
    user: Annotated[User, Depends(get_current_user)],
    before: str = "",
    limit: int = DEFAULT_PAGE_SIZE,
) -> dict:
    """One page of a conversation, newest first, oldest-first within the page.

    The unpaged sibling above returns every message a conversation has ever
    held. That is fine for provenance tooling and wrong for a panel someone
    opens twenty times a day.

    `before` is the `next_before` from a previous response. Omit it for the
    newest page.
    """
    limit = max(1, min(limit, MAX_PAGE_SIZE))
    # pylint: disable=protected-access
    conv = await service._repo.find_or_create_conversation(user.id, conversation_key)
    rows = await service._repo.page_messages(
        conv.id, limit=limit, before=_decode_cursor(before),
    )
    # pylint: enable=protected-access
    messages = [
        {
            "id": m.id,
            "role": m.role,
            "content": m.content,
            "created_at": m.created_at.isoformat(),
            "tokens_in": m.tokens_in,
            "tokens_out": m.tokens_out,
            "model": m.model,
            "extras": m.extras or {},
        }
        for m in rows
    ]
    # A full page means there is probably more; a short one means there is
    # not. Cheaper than a count, and the cost of being wrong is one request
    # that comes back empty.
    has_more = len(rows) == limit
    return {
        "conversation_key": conversation_key,
        "messages": messages,
        "has_more": has_more,
        "next_before": _encode_cursor(messages[0]) if has_more and messages else "",
    }


@router.get("/conversations/{conversation_key:path}",
            response_model=ConversationResponse)
@inject
async def get_conversation(
    conversation_key: str,
    *,
    service: FromDishka[AssistantService],
    user: Annotated[User, Depends(get_current_user)],
) -> dict:
    """Return the full stored history for a conversation key, scoped to the user."""
    # AssistantService's public surface is turn-based (chat / usage);
    # there's no dedicated "fetch a stored conversation" verb because
    # the only consumer is this introspection endpoint. Reach through
    # to the repo handle.
    # pylint: disable=protected-access
    conv = await service._repo.find_or_create_conversation(user.id, conversation_key)
    messages = await service._repo.list_messages(conv.id)
    # pylint: enable=protected-access
    return {
        "conversation_key": conversation_key,
        "messages": [
            {
                "id": m.id,
                "role": m.role,
                "content": m.content,
                "created_at": m.created_at.isoformat(),
                "tokens_in": m.tokens_in,
                "tokens_out": m.tokens_out,
                "model": m.model,
                # Tool rows carry the call's arguments here. The result is
                # deliberately not stored, so there is nothing else to send:
                # what was called and with what is the part that says whether
                # the agent did what was asked.
                "extras": m.extras or {},
            }
            for m in messages
        ],
    }


#: Keys the switcher shows. A report's chat belongs to that report and opens
#: with it; listing it here would fill the sidebar with entries nobody chose
#: to start.
STANDALONE_PREFIX = "chat:"

#: Longest auto-title taken from an opening question.
TITLE_CHARS = 60


def _auto_title(text: str) -> str:
    """A title from the first thing asked, for a conversation with none.

    Nobody names a chat before having it, so the opening question is the only
    thing available at the moment a title is needed. Truncated on a word
    boundary where there is one, because a title cut mid-word reads as broken
    rather than as shortened.
    """
    flat = " ".join((text or "").split())
    if len(flat) <= TITLE_CHARS:
        return flat
    cut = flat[:TITLE_CHARS]
    head, _, _ = cut.rpartition(" ")
    return (head or cut) + "…"


class ConversationCreate(BaseModel):
    title: str = Field("", max_length=200)


class ConversationRename(BaseModel):
    title: str = Field(..., min_length=1, max_length=200)


@router.get("/conversations", response_model=ConversationListResponse)
@inject
async def list_conversations(
    *,
    service: FromDishka[AssistantService],
    user: Annotated[User, Depends(get_current_user)],
) -> dict:
    """Every conversation the user has, newest activity first.

    Report chats and the global chat are listed too, not just standalone
    ones. Hiding them made a prompt sent from a report page vanish into a
    chat no list would ever show again.
    """
    # pylint: disable=protected-access
    rows = await service._repo.list_conversations(user.id)
    # pylint: enable=protected-access
    return {
        "conversations": [
            {
                "conversation_key": c.conversation_key,
                "title": c.title or _auto_title(c.last_snippet) or "",
                "updated_at": c.updated_at.isoformat(),
                "message_count": c.message_count,
                "last_snippet": c.last_snippet,
            }
            for c in rows
        ]
    }


@router.post("/conversations", status_code=201)
@inject
async def create_conversation(
    body: ConversationCreate,
    *,
    service: FromDishka[AssistantService],
    user: Annotated[User, Depends(get_current_user)],
) -> dict:
    """Mint a new standalone conversation and return its key.

    The key is minted here rather than accepted from the caller: it is the
    identity the messages hang off, and a client-chosen one is a client-chosen
    way into somebody else's rows.
    """
    key = f"{STANDALONE_PREFIX}{uuid4()}"
    # pylint: disable=protected-access
    conv = await service._repo.find_or_create_conversation(user.id, key)
    if body.title:
        await service._repo.rename_conversation(user.id, key, body.title)
    await service._repo.commit()
    # pylint: enable=protected-access
    return {
        "conversation_key": conv.conversation_key,
        "title": body.title,
        "updated_at": conv.updated_at.isoformat(),
        "message_count": 0,
        "last_snippet": "",
    }


@router.patch(
    "/conversations/{conversation_key:path}",
    responses={404: {"description": "No such conversation for this user."}},
)
@inject
async def rename_conversation(
    conversation_key: str,
    body: ConversationRename,
    *,
    service: FromDishka[AssistantService],
    user: Annotated[User, Depends(get_current_user)],
) -> dict:
    # pylint: disable=protected-access
    ok = await service._repo.rename_conversation(
        user.id, conversation_key, body.title.strip(),
    )
    if ok:
        await service._repo.commit()
    # pylint: enable=protected-access
    if not ok:
        # 404 rather than 403: saying "exists, but not yours" is what an
        # enumeration attack needs.
        raise HTTPException(status_code=404, detail="No such conversation.")
    return {"conversation_key": conversation_key, "title": body.title.strip()}


@router.delete(
    "/conversations/{conversation_key:path}",
    responses={404: {"description": "No such conversation for this user."}},
)
@inject
async def delete_one_conversation(
    conversation_key: str,
    *,
    service: FromDishka[AssistantService],
    user: Annotated[User, Depends(get_current_user)],
) -> dict:
    """Delete one conversation.

    The sibling DELETE /conversations deletes every conversation the user has.
    That was survivable while there were two; with a switcher full of them, a
    control that says "delete" and means "delete everything" is a data-loss
    report waiting to happen. This is the one a delete button should call.
    """
    # pylint: disable=protected-access
    ok = await service._repo.delete_conversation(user.id, conversation_key)
    if ok:
        await service._repo.commit()
    # pylint: enable=protected-access
    if not ok:
        raise HTTPException(status_code=404, detail="No such conversation.")
    return {"deleted": conversation_key}


# ── Provider credentials ──────────────────────────────────────
#
# Write-only, the way a password is: a key goes in and never comes back
# out through the API. Callers get a fingerprint so they can tell WHICH
# key is stored without being shown any part of it.


class ProviderCredentialIn(BaseModel):
    provider: str = Field(..., description=f"One of: {', '.join(SUPPORTED_PROVIDERS)}")
    api_key: str = Field(..., min_length=8, description="Your own provider API key.")
    model: str | None = Field(
        None, description="Optional model override, e.g. 'claude-sonnet-4-5'.",
    )


@router.put(
    "/credentials",
    status_code=200,
    responses={
        422: {"description": "Unsupported provider."},
        503: {"description": "Credential encryption is not configured."},
    },
)
@inject
async def put_credential(
    body: ProviderCredentialIn,
    repo: FromDishka[CredentialRepository],
    user: Annotated[User, Depends(get_current_user)],
) -> dict:
    """Store or replace the caller's key for one provider."""
    try:
        provider = validate_provider(body.provider)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    try:
        summary = await repo.upsert(
            user_id=user.id, provider=provider,
            secret=body.api_key.strip(), model=(body.model or None),
        )
    except CredentialEncryptionUnavailable as exc:
        # Never store a secret we cannot protect; 503 because this is our
        # misconfiguration, not the caller's mistake.
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    return summary.as_dict()


@router.get("/models", response_model=ModelListResponse)
@inject
async def list_models(
    *,
    model_prefs: FromDishka[ModelPreferenceRepository],
    credentials: FromDishka[CredentialRepository],
    user: Annotated[User, Depends(get_current_user)],
):
    """The built-in models on offer, which one this user picked, and
    whether the choice currently has any effect.

    `active` is false when the user has stored their own provider key: the
    turn spends that instead, so offering a built-in model picker would be
    a control that changes nothing. The caller needs to be told rather than
    having to infer it from a separate credentials call.
    """
    try:
        has_own_key = bool(await credentials.list_for_user(user.id))
    except CredentialEncryptionUnavailable:
        # No master key: nobody's stored key can be spent this turn, so the
        # built-in is what runs and the picker does apply.
        has_own_key = False
    return {
        "models": local_models.as_dicts(),
        "selected": await model_prefs.get(user.id),
        "active": not has_own_key,
    }


class ModelChoiceBody(BaseModel):
    """A curated id from local_models, not a model name."""

    model_id: str = Field(..., max_length=64)


@router.put(
    "/models",
    responses={422: {"description": "Unknown model id."}},
)
@inject
async def choose_model(
    body: ModelChoiceBody,
    *,
    model_prefs: FromDishka[ModelPreferenceRepository],
    user: Annotated[User, Depends(get_current_user)],
):
    """Pick a built-in model.

    Rejects anything not on the list rather than storing it: a saved id we
    do not honour would fall back at every turn and look like the setting
    had been ignored.
    """
    try:
        selected = await model_prefs.set(user.id, body.model_id)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    return {"selected": selected}


@router.get("/credentials")
@inject
async def list_credentials(
    repo: FromDishka[CredentialRepository],
    user: Annotated[User, Depends(get_current_user)],
) -> dict:
    """Which providers the caller has configured. Never the keys."""
    return {
        "supported": list(SUPPORTED_PROVIDERS),
        # What the user gets with no key of their own. Reported by the
        # server rather than hardcoded in the frontend so swapping the
        # hosted weights does not need a web release. Null when no local
        # server is configured, which is the frontend's signal to go back
        # to saying a key is required.
        "builtin": (
            {"model": os.environ.get("LOCAL_LLM_MODEL", "qwen3-4b")}
            if os.environ.get("LOCAL_LLM_URL")
            else None
        ),
        "credentials": [c.as_dict() for c in await repo.list_for_user(user.id)],
    }


@router.delete(
    "/credentials/{provider}",
    status_code=204,
    responses={
        404: {"description": "No credential stored for that provider."},
        422: {"description": "Unsupported provider."},
    },
)
@inject
async def delete_credential(
    provider: str,
    repo: FromDishka[CredentialRepository],
    user: Annotated[User, Depends(get_current_user)],
) -> None:
    """Remove a stored key. Deletion has to actually delete."""
    try:
        provider = validate_provider(provider)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    if not await repo.delete(user.id, provider):
        raise HTTPException(status_code=404, detail="No credential for that provider")


# ── MCP access tokens ─────────────────────────────────────────
#
# What a user pastes into their own LLM client so it can reach Fontem's
# tools. Shown once at creation and never again: a token that can be
# re-read is a token an attacker can re-read.


class McpTokenIn(BaseModel):
    label: str = Field("", max_length=80,
                       description="Which client this is for, e.g. 'Claude Desktop'.")


@router.post("/mcp-tokens", status_code=201)
@inject
async def create_mcp_token(
    body: McpTokenIn,
    repo: FromDishka[McpTokenRepository],
    user: Annotated[User, Depends(get_current_user)],
) -> dict:
    """Mint a token. The plaintext is in this response and nowhere else."""
    plaintext, summary = await repo.create(user.id, body.label)
    return {**summary.as_dict(), "token": plaintext}


@router.get("/mcp-tokens")
@inject
async def list_mcp_tokens(
    repo: FromDishka[McpTokenRepository],
    user: Annotated[User, Depends(get_current_user)],
) -> dict:
    """Which clients are connected. Never the tokens themselves."""
    return {"tokens": [t.as_dict() for t in await repo.list_for_user(user.id)]}


@router.delete(
    "/mcp-tokens/{token_id}",
    status_code=204,
    responses={404: {"description": "No such token."}},
)
@inject
async def revoke_mcp_token(
    token_id: str,
    repo: FromDishka[McpTokenRepository],
    user: Annotated[User, Depends(get_current_user)],
) -> None:
    """Disconnect a client."""
    if not await repo.revoke(user.id, token_id):
        raise HTTPException(status_code=404, detail="No such token")


@router.post(
    "/mcp-tokens/verify",
    include_in_schema=False,
    responses={401: {"description": "Invalid or revoked token."}},
)
@inject
async def verify_mcp_token(
    body: dict,
    repo: FromDishka[McpTokenRepository],
) -> dict:
    """Internal: resolve a token to a user for the MCP server.

    Not in the public schema and not reachable from outside the cluster.
    The MCP server calls this rather than re-implementing verification —
    a second verifier is a second place for the rules to drift.
    """
    user_id = await repo.verify((body or {}).get("token", ""))
    if not user_id:
        raise HTTPException(status_code=401, detail="Invalid token")
    return {"user_id": user_id}
