"""AssistantService — the public entry point of the assistant module.

Callers (the router, future background jobs, other services) talk to
this class and this class alone. It:

  1. loads conversation history from its repository,
  2. budget-truncates the context and history,
  3. builds the system prompt,
  4. streams the response through a pluggable proxy client,
  5. records user + assistant rows with token counts,
  6. answers usage queries.

The proxy client is a small interface (``stream(payload) -> async iter of str``).
In production it's the httpx-based ``ClaudeProxyClient``; in tests it's a
fake. The service itself has no httpx dependency.
"""
# pylint: disable=missing-class-docstring,missing-function-docstring
# pylint: disable=too-many-arguments,too-many-positional-arguments,too-many-locals
# pylint: disable=too-few-public-methods,import-outside-toplevel
from __future__ import annotations

import json
from collections.abc import AsyncIterator
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import AsyncIterator as TypingAsyncIterator, Protocol

from src.assistant import (
    context_budget,
    schema_context,
    local_models,
    navigation,
    summariser,
    tool_budget,
)
from src.assistant.tool_runtime import _sse as _sse_event
from src.services import audit_context
from src.assistant.context import (
    TurnLimits,
    budget_context_block,
    build_system_prompt,
    fit_history,
)
from src.assistant.doc_ops import DocOps
from src.assistant.repository import AssistRepository, DailyUsage
from src.assistant.tokens import (
    TokenUsage,
    estimate_tokens,
    parse_sse_usage,
)


# ── Public data types ──────────────────────────────────────────


@dataclass(frozen=True)
# A turn genuinely carries this much: who is asking, in which conversation,
# what they said, what is on screen, where they are, whose key pays, and
# which model. Splitting it into sub-objects would only move the count.
# pylint: disable=too-many-instance-attributes
class ChatRequest:
    #: None for a signed-out visitor. Every persistence path in `turn` keys
    #: off this being set: an anonymous turn writes no conversation, no
    #: messages, no tool rows, no usage and no activity. That is the point
    #: rather than a simplification — `assist_conversations.user_id` is NOT
    #: NULL, and the alternative (mint a synthetic id per visitor) would let
    #: unauthenticated traffic write unbounded rows into the tables the usage
    #: reports read.
    user_id: str | None
    conversation_key: str
    message: str
    context_block: str
    #: Whether the caller has an editing surface to propose into. None for
    #: clients that predate the field; see `turn` for the fallback.
    has_editor: bool | None = None
    #: Current location + the site map, generated by the frontend from its
    #: own router and sent with the turn. See src/assistant/navigation.py
    #: for why it is not held server-side.
    nav: dict | None = None
    #: The caller's own provider credential, resolved before the turn.
    #: (provider, api_key, model) or None when they have not configured
    #: one — in which case the turn falls back to the platform key if one
    #: is still configured, and otherwise fails with a legible message.
    credential: tuple[str, str, str | None] | None = None
    #: Which built-in model to use when there is no credential. A curated
    #: id from src/assistant/local_models.py, resolved to a served name by
    #: the proxy client — never a filename from the caller.
    local_model_id: str | None = None


#: How long a signed-out visitor's message may be.
#:
#: The reduced assistant answers questions about the platform and moves the
#: caller around it. Those questions are short. A cap keeps the shape of the
#: turn honest — an unauthenticated caller cannot use the prompt as a way to
#: buy a large context on the shared llama-server, which the 20/hour limit
#: alone would not stop (one request can be as long as the body allows).
#:
#: `context_block` needs no equivalent: it is already truncated to the
#: service's own char budget before it reaches the model.
#:
#: fontem-web mirrors this number in AssistPanel.vue so the input stops the
#: user before the request does. Rejected rather than truncated: a silently
#: shortened question gets a confident answer to something nobody asked.
ANONYMOUS_MAX_PROMPT_CHARS = 1_000


@dataclass(frozen=True)
class UsageSnapshot:
    tokens_1h: int
    tokens_24h: int
    tokens_7d: int


# ── Proxy client protocol ──────────────────────────────────────


class ProxyClient(Protocol):
    """Anything that takes a payload and yields SSE lines back."""

    def stream(
        self, payload: dict
    ) -> TypingAsyncIterator[str]:  # pragma: no cover - protocol
        ...


# ── Service ────────────────────────────────────────────────────


def _cap(value: object, limit: int) -> str:
    """One stored tool result, bounded. Non-strings are not stored."""
    if not isinstance(value, str):
        return ""
    return value if len(value) <= limit else value[:limit]


class AssistantService:

    def __init__(
        self,
        repo: AssistRepository,
        proxy_client: ProxyClient,
        base_system_prompt: str,
        turn_limits: TurnLimits,
        context_char_budget: int,
        project_service=None,
        #: Characters of system prompt + tool schemas that every turn carries
        #: before any conversation. Measured at wiring time rather than
        #: guessed: it is the same for every turn, and guessing it is how a
        #: budget overflows in production but not in a test.
        fixed_prefix_chars: int = 7_176,
        #: Best-effort provider of the rendered graph-schema prompt block
        #: (see schema_context). None keeps every existing wiring working.
        schema_provider=None,
        #: ReportService (or None). Enables the document tools: read_document
        #: and the proposal verbs are bound per turn to the report the
        #: conversation key names, as the asking user.
        report_service=None,
        #: Tokens reserved for the model's own reply. Not slack — a window
        #: that fits the conversation and leaves nothing to answer with fails
        #: the same way an overflow does, one step later.
        reply_tokens: int = 4_000,
    ) -> None:
        self._repo = repo
        self._proxy = proxy_client
        self._base_prompt = base_system_prompt
        self._turn_limits = turn_limits
        self._fixed_prefix_chars = fixed_prefix_chars
        self._schema = schema_provider
        self._reports = report_service
        self._reply_tokens = reply_tokens
        self._context_budget = context_char_budget
        self._projects = project_service

    # ─────────── Turn handling ────────────

    # NOSONAR S3776: SSE stream reconciliation is inherently sequential.
    # The branch and statement counts are the SSE vocabulary itself — one
    # arm per event type the panel understands — so splitting it would move
    # the count rather than reduce what a reader has to hold.
    # pylint: disable=too-many-branches,too-many-statements
    async def turn(self, req: ChatRequest) -> AsyncIterator[str]:
        """Handle a single chat turn, streaming SSE lines back to the caller.

        Persists a user row before calling the proxy (so even cancelled
        turns are visible in usage reports), then persists an assistant
        row on stream completion with real token counts if the proxy
        forwarded them, otherwise with estimates.

        A signed-out visitor takes a different route entirely — see
        `_anonymous_turn`. Branching here rather than threading `if user_id`
        through the body keeps the two shapes legible: the authenticated turn
        is largely about persistence and provenance, and the anonymous one
        has neither.
        """
        if req.user_id is None:
            async for line in self._anonymous_turn(req):
                yield line
            return

        conv = await self._repo.find_or_create_conversation(
            req.user_id, req.conversation_key
        )

        # Build history view for the LLM, from persisted rows only.
        #
        # The window is sized from the model this turn will actually run on,
        # not from a module constant. The constant was sized for the smallest
        # context we serve, which handed a 1M-token model the same ~7,700
        # tokens of conversation as a 32k one.
        # The schema block is tiered: models whose context clears the
        # threshold carry it in prefill; smaller ones keep the get_schema
        # tool instead. Fetched before the budget is derived, because a
        # prefix the budget does not know about is how windows overflow in
        # production and nowhere else.
        schema_block = ""
        if self._schema is not None and schema_context.wants_schema(
                local_models.resolve(req.local_model_id).context_tokens):
            schema_block = await self._schema.block()

        stored = await self._repo.history_turns(conv.id)
        # What the stored summary already covers is represented by the
        # summary, not by the turns themselves — otherwise they fall off again
        # every turn and get folded in again, and the summary restates itself.
        prior = summariser.unsummarised(stored, conv.summary_through)
        windowed, overflow = fit_history(
            prior,
            self._limits_for(req.local_model_id,
                             extra_prefix_chars=len(schema_block)),
        )

        # Summarise only what just fell off, and only when something did.
        #
        # A conversation that fits its budget produces no summary and pays for
        # none — on a 1M-token model that is effectively every conversation.
        # When turns do fall off, dropping them silently is what makes a long
        # chat start contradicting decisions taken earlier in itself.
        summary = conv.summary
        if overflow:
            summary = await self._roll_summary(conv, summary, overflow, req)
        if summary:
            windowed = [summariser.render(summary), *windowed]

        budgeted_context = budget_context_block(
            req.context_block, char_budget=self._context_budget
        )
        # The site map is built here rather than appended by the proxy
        # client so it lands ahead of the volatile sections. It is static
        # for the whole conversation, and anything after a section that
        # changes gets re-prefilled every turn.
        system_prompt = build_system_prompt(
            self._base_prompt,
            budgeted_context,
            windowed,
            site_map=navigation.system_context(req.nav),
            schema_block=schema_block,
        )

        # Persist the user row immediately with an estimate.
        # If the proxy forwards real usage later, we'll reconcile.
        estimated_in = estimate_tokens(req.message) + estimate_tokens(budgeted_context)
        user_row = await self._repo.append_message(
            conversation_id=conv.id,
            user_id=req.user_id,
            role="user",
            content=req.message,
            tokens_in=estimated_in,
            tokens_out=None,
            model=None,
        )

        # Stream through the proxy, accumulating text for the assistant row.
        assistant_buf: list[str] = []
        real_usage: TokenUsage | None = None
        errored = False
        # Which model actually answered. Stored on the assistant row, because
        # "was the 1.7B or the 4B asked to do this" is unanswerable after the
        # fact otherwise — and every row in production was NULL.
        answered_by = req.local_model_id
        if req.credential:
            answered_by = req.credential[2] or req.credential[0]

        payload: dict = {
            "system": system_prompt,
            "message": req.message,
            "nav": req.nav,
            # The assistant is on every page now, so the tool surface has
            # to follow the user: propose_edit means nothing without an
            # article open.
            #
            # Trust the client's flag. This used to be inferred from
            # `bool(req.context_block)` — whether the article had any TEXT
            # — which is not the same question. A story that has just been
            # created has no body yet, so the tool was withdrawn at exactly
            # the moment the user asked for their first paragraph, and the
            # model, offered no way to propose, searched the graph instead.
            # Measured against staging: identical prompt and model, empty
            # context_block called propose_edit 0/4, non-empty 1/1.
            #
            # The client holds the report id and the editor state and needs
            # both to apply a proposal, so it is the only place that can
            # answer this. The old inference stays as the fallback for
            # clients that do not send the field.
            "has_editor": (bool(req.context_block) if req.has_editor is None
                           else bool(req.has_editor)),
        }
        # From here until the stream ends, anything written on this user's
        # behalf is the assistant's doing. The tools call the services
        # in-process, so nothing about the transport would say so — this is
        # the only place that knows.
        audit_token = audit_context.set_current(
            audit_context.current().derive(
                actor_id=req.user_id,
                actor_kind=audit_context.AGENT,
                conversation_id=conv.id,
                message_id=None,
            )
        )

        if (self._reports is not None
                and req.conversation_key.startswith("report:")
                and payload["has_editor"]):
            # Bound to THIS user and THIS report for this turn only — the
            # same shape as studio_ops below, for the same reason. Gated on
            # the editor because the whole surface is: reading a document
            # you cannot propose into invites edits with nowhere to land.
            payload["doc_ops"] = DocOps(
                self._reports, req.user_id,
                req.conversation_key.split(":", 1)[1],
            )

        if self._projects is not None:
            # An object, not JSON: these clients run in-process, and the
            # alternative is re-authenticating the user over HTTP to this
            # same service. Bound to this user for this turn only.
            #
            # Always built. The Studio tools act on the user's own projects
            # and the service checks access per call, so there is no state
            # the caller has to be "in" for them to be usable — and gating
            # them on an open project stopped the agent using the very tool
            # that creates one.
            from src.assistant.studio_ops import StudioOps
            payload["studio_ops"] = StudioOps(self._projects, req.user_id)

        if req.local_model_id:
            payload["local_model_id"] = req.local_model_id
        # The per-turn tool-output ceiling, sized to THIS model's context —
        # but only for models at or above the schema tier. The first cut
        # scaled it for everyone, and the staging e2e caught what that does
        # to a small local model: doubling the 1.7B's tool input roughly
        # doubles its prefill per round on the shared iGPU, and the real-
        # model smoke turns blew straight past their 200s wait (attest runs
        # 27451/27452). Small models keep the floor they were measured at;
        # the scaling exists for the frontier models whose investigations
        # the flat 14k cap was strangling (reported live, 2026-08-28).
        # A BYOK credential means a frontier model whose real window we
        # don't know; assume the schema-tier boundary.
        if req.credential:
            payload["tool_chars"] = self._budget_for_context(
                schema_context.SCHEMA_MIN_CONTEXT_TOKENS).tool_chars
        else:
            model = local_models.resolve(req.local_model_id)
            payload["tool_chars"] = (
                self._tool_chars_for(req.local_model_id)
                if model.context_tokens
                >= schema_context.SCHEMA_MIN_CONTEXT_TOKENS
                else tool_budget.MAX_TOOL_RESULT_CHARS_PER_TURN
            )
        if req.credential:
            # Spending the user's own key, not the platform's. Passed per
            # turn rather than held on the client instance, because the
            # client is an APP-scoped singleton shared by every request —
            # storing a key on it would leak one user's credential into
            # another user's turn.
            provider, api_key, model = req.credential
            payload["credential"] = {
                "provider": provider, "api_key": api_key, "model": model,
            }

        async for line in self._proxy.stream(payload):
            yield line
            parsed = _parse_sse_line(line)
            if parsed is None:
                continue
            event, data = parsed
            if event == "chunk":
                text = _extract_chunk_text(data)
                if text:
                    assistant_buf.append(text)
            elif event == "tool_result":
                # One row per tool call: what was called, with which
                # arguments, and what came back. The result is capped at
                # MAX_TOOL_RESULT_CHARS so a tool returning 90k of JSON
                # cannot make the conversation store mostly tool output.
                # The id is the one minted where the call ran, so an
                # activity entry can point straight at this row.
                await self._persist_tool_call(conv.id, req.user_id, data)
            elif event == "error":
                errored = True
            else:
                usage = parse_sse_usage(event, data)
                if usage is not None:
                    real_usage = usage

        # Only persist the assistant row if we actually accumulated text.
        # An error-before-any-chunks turn leaves a dangling user row — that's
        # intentional: the user's token budget was spent on the failed attempt.
        if assistant_buf:
            assistant_text = "".join(assistant_buf)
            tokens_out = (
                real_usage.output_tokens
                if real_usage is not None
                else estimate_tokens(assistant_text)
            )
            await self._repo.append_message(
                conversation_id=conv.id,
                user_id=req.user_id,
                role="assistant",
                content=assistant_text,
                tokens_in=None,
                tokens_out=tokens_out,
                model=answered_by,
            )

            # Replace the estimate with what the model actually counted.
            if real_usage is not None and real_usage.input_tokens:
                await self._repo.set_tokens_in(
                    user_row.id, real_usage.input_tokens
                )

        # The turn is over; later work on this request is the user's again.
        audit_context.reset(audit_token)

        # Commit all writes so they survive regardless of how the
        # HTTP framework manages the session lifecycle (e.g. streaming
        # responses where framework cleanup may run too late).
        await self._repo.commit()

        if errored and not assistant_buf:
            return

    async def _anonymous_turn(self, req: ChatRequest) -> AsyncIterator[str]:
        """One turn for a visitor who is not signed in.

        A wayfinder rather than the assistant: it can talk about the platform
        and move the caller around it, and that is the whole of it. Three
        things make it that, and each is decided here rather than asked of
        the model:

        * `anonymous` in the payload, which collapses the tool surface to
          `navigate` alone in whichever engine is driving, and is checked
          again when a call is dispatched.
        * the smallest model we offer, whatever the caller asked for. There
          is no credential path either: an unauthenticated request must not
          be able to name the model that answers it, or the cheap tier is a
          suggestion.
        * no writes. Nothing is persisted, so there is no conversation to
          resume — each turn stands alone, and what the visitor sees of their
          own history lives in the browser for as long as the tab does.

        No audit context is installed. Nothing here can write, so there would
        be nothing to attribute; leaving the ambient context alone also means
        an anonymous turn cannot be mistaken for an agent acting on some
        user's behalf.
        """
        budgeted_context = budget_context_block(
            req.context_block, char_budget=self._context_budget
        )
        system_prompt = build_system_prompt(
            self._base_prompt,
            budgeted_context,
            # No history, because none is stored and none can be: the model
            # is told the truth about what it knows.
            [],
            site_map=navigation.system_context(req.nav),
        )
        payload = {
            "system": system_prompt,
            "message": req.message,
            "nav": req.nav,
            # Nothing to propose into, and no account to propose for.
            "has_editor": False,
            "anonymous": True,
            # Not the constant directly: the accessor refuses to hand an
            # anonymous turn a model the platform pays for.
            "local_model_id": local_models.anonymous_model_id(),
        }
        # Say OUT LOUD that this is the reduced assistant, first, before any
        # content. The signed-out tier is a deliberate product decision; the
        # silence about it was not: a visitor whose session had expired got
        # the smallest model with navigate as its only tool and no memory,
        # while the panel looked exactly like the full assistant — the turn
        # "worked", investigated nothing, and could not understand
        # "continue". The client renders this into a visible notice.
        yield _sse_event("meta", {
            "anonymous": True,
            "model": local_models.anonymous_model_id(),
            "detail": ("Signed-out assistant: smallest model, navigation "
                       "only, no conversation memory."),
        })
        async for line in self._proxy.stream(payload):
            yield line

    async def _roll_summary(
        self, conv, previous: str, dropped: list, req,
    ) -> str:
        """Fold the newly dropped turns into the rolling summary.

        Best-effort by design. A summariser that fails must not take down the
        turn the user is waiting on: the window is already correct without a
        summary, it is merely poorer. Returning `previous` keeps whatever was
        already known rather than discarding it on a transient failure.
        """
        request = summariser.build_request(previous, dropped)
        if not request:
            return previous

        payload: dict = {
            "system": summariser.SYSTEM_PROMPT,
            "message": request,
            "nav": None,
            # No tools and no editor: this call reads text and returns text.
            # Handing it the tool surface invites it to go looking things up
            # mid-summary, which is neither wanted nor paid for.
            "has_editor": False,
        }
        if req.local_model_id:
            payload["local_model_id"] = req.local_model_id
        if req.credential:
            provider, api_key, model = req.credential
            payload["credential"] = {
                "provider": provider, "api_key": api_key, "model": model,
            }

        buf: list[str] = []
        try:
            async for line in self._proxy.stream(payload):
                parsed = _parse_sse_line(line)
                if parsed is None:
                    continue
                event, data = parsed
                if event == "chunk":
                    text = _extract_chunk_text(data)
                    if text:
                        buf.append(text)
                elif event == "error":
                    return previous
        except Exception:  # pylint: disable=broad-except
            # Deliberately broad: every transport failure mode reaching here
            # has the same right answer, which is to answer the user anyway.
            return previous

        rolled = summariser.cap("".join(buf))
        if not rolled:
            return previous
        await self._repo.set_summary(conv.id, rolled, dropped[-1].message_id or "")
        return rolled

    def _tool_chars_for(self, local_model_id: str | None) -> int:
        """This turn's ceiling on all tool output, together.

        The same derivation as the history window, using the other half of
        the split. `MAX_TOOL_RESULT_CHARS_PER_TURN` stays the floor, so no
        model gets less room for tool output than it had before — but a model
        with a large context stops being held to a number that was sized
        against a 16k window.
        """
        return self._budget_for(local_model_id).tool_chars

    def _budget_for(
        self, local_model_id: str | None, extra_prefix_chars: int = 0,
    ) -> context_budget.ContextBudget:
        model = local_models.resolve(local_model_id)
        return self._budget_for_context(
            model.context_tokens, extra_prefix_chars)

    def _budget_for_context(
        self, context_tokens: int, extra_prefix_chars: int = 0,
    ) -> context_budget.ContextBudget:
        return context_budget.derive(
            context_tokens=context_tokens,
            fixed_prefix_chars=self._fixed_prefix_chars + extra_prefix_chars,
            reply_tokens=self._reply_tokens,
            floor_history_chars=self._turn_limits.max_chars,
            floor_tool_chars=tool_budget.MAX_TOOL_RESULT_CHARS_PER_TURN,
        )

    def _limits_for(
        self, local_model_id: str | None, extra_prefix_chars: int = 0,
    ) -> TurnLimits:
        """Turn limits sized to the model this turn will run on.

        `self._turn_limits` stays the floor: whatever the arithmetic says, no
        model gets a smaller window than the fixed constant it had before.

        Constructed rather than `replace`d: dataclasses.replace is typed as
        returning DataclassInstance, so the -> TurnLimits annotation would be
        a claim the type checker cannot support.
        """
        return TurnLimits(
            max_turns=self._turn_limits.max_turns,
            max_chars=self._budget_for(
                local_model_id, extra_prefix_chars).history_chars,
            keep_fraction=self._turn_limits.keep_fraction,
        )

    async def _persist_tool_call(
        self, conversation_id: str, user_id: str, data: str
    ) -> None:
        """Record one tool call from its `tool_result` event.

        Best-effort on parsing only: a malformed event must not take down a
        turn that is otherwise working. A failure to WRITE is not swallowed —
        it belongs to the same transaction as the rest of the turn.
        """
        try:
            payload = json.loads(data)
        except (ValueError, TypeError):
            return
        if not isinstance(payload, dict):
            return
        name = payload.get("tool") or ""
        if not name:
            return
        await self._repo.append_message(
            conversation_id=conversation_id,
            user_id=user_id,
            role="tool",
            content=name,
            tokens_in=None,
            tokens_out=None,
            model=None,
            extras={
                "args": payload.get("args") or {},
                "elapsed": payload.get("elapsed"),
                # How much the tool produced, before any capping.
                "bytes": payload.get("bytes"),
                "truncated": bool(payload.get("truncated")),
                # The result now travels with the call.
                #
                # It used to be dropped so the store would not become mostly
                # tool output, which also meant the next turn had no idea what
                # the last one found — the model would re-run a search it had
                # already run, and the panel rendered historical tool bubbles
                # with an empty body. Capped at the same ceiling that binds a
                # result on its way into the model, so one row cannot be
                # unbounded either.
                "result": _cap(payload.get("result"), tool_budget.MAX_TOOL_RESULT_CHARS),
            },
            message_id=payload.get("call_id") or None,
        )

    # ─────────── Provenance ────────────

    async def turn_for_message(
        self, user_id: str, message_id: str
    ) -> dict | None:
        """The turn a given message belongs to: prompt, tool calls, answer.

        This is what makes an activity entry explainable. The entry names the
        tool call that caused it; this reassembles what the user actually
        asked and everything the agent did in that turn, so "the assistant
        created this project" can be read back as a sequence rather than
        taken on faith.

        Returns None when the message does not exist OR does not belong to
        the caller — the same answer for both, because distinguishing them
        tells a stranger whether an id is real.

        The turn is delimited by messages, not by a stored turn id: the rows
        for one exchange are the user message, every tool call after it, and
        the assistant message that ends it. That is inherent to the ordering
        rather than a convention someone has to maintain.
        """
        msg = await self._repo.get_message(message_id)
        if msg is None or msg.user_id != user_id:
            return None

        messages = await self._repo.list_messages(msg.conversation_id)
        try:
            here = next(i for i, m in enumerate(messages) if m.id == message_id)
        except StopIteration:  # pragma: no cover - it was just fetched
            return None

        # Walk back to the prompt that opened this turn.
        start = 0
        for i in range(here, -1, -1):
            if messages[i].role == "user":
                start = i
                break
        # ...and forward to the answer that closed it.
        end = len(messages)
        for i in range(here + 1, len(messages)):
            if messages[i].role == "user":
                end = i
                break

        window = messages[start:end]
        prompt = next((m for m in window if m.role == "user"), None)
        answer = next((m for m in window if m.role == "assistant"), None)
        return {
            "conversation_id": msg.conversation_id,
            "message_id": message_id,
            "prompt": _prompt_of(prompt),
            "calls": [
                _call_of(m, subject=message_id)
                for m in window if m.role == "tool"
            ],
            "answer": _answer_of(answer),
        }

    # ─────────── Usage queries ────────────

    async def usage_for_user(
        self, user_id: str, now: datetime | None = None
    ) -> UsageSnapshot:
        now = now or datetime.now(timezone.utc)
        tokens_1h = await self._repo.tokens_used_since(user_id, now - timedelta(hours=1))
        tokens_24h = await self._repo.tokens_used_since(user_id, now - timedelta(hours=24))
        tokens_7d = await self._repo.tokens_used_since(user_id, now - timedelta(days=7))
        return UsageSnapshot(
            tokens_1h=tokens_1h,
            tokens_24h=tokens_24h,
            tokens_7d=tokens_7d,
        )

    async def delete_user_conversations(self, user_id: str) -> int:
        """Delete all conversations and messages for a user. Returns count deleted."""
        count = await self._repo.delete_user_conversations(user_id)
        await self._repo.commit()
        return count

    async def usage_history_for_user(
        self,
        user_id: str,
        days: int,
        now: datetime | None = None,
    ) -> list[DailyUsage]:
        """Per-day token totals for the last ``days`` days (ending now)."""
        now = now or datetime.now(timezone.utc)
        since = now - timedelta(days=days)
        return await self._repo.usage_history_since(user_id, since)


def _at(message) -> str | None:
    """An ISO timestamp, for rows that may predate one."""
    return message.created_at.isoformat() if message.created_at else None


def _prompt_of(message) -> dict | None:
    """What the user asked. None for a turn whose prompt is gone."""
    if message is None:
        return None
    return {"content": message.content, "created_at": _at(message)}


def _answer_of(message) -> dict | None:
    """What the assistant replied, and which model wrote it. None when the
    turn errored before answering — which is exactly when someone asks."""
    if message is None:
        return None
    return {
        "content": message.content,
        "model": message.model,
        "created_at": _at(message),
    }


def _call_of(message, *, subject: str) -> dict:
    """One tool call. No result: it was never stored."""
    extras = message.extras or {}
    return {
        "id": message.id,
        "tool": message.content,
        "args": extras.get("args") or {},
        "elapsed": extras.get("elapsed"),
        "bytes": extras.get("bytes"),
        "truncated": bool(extras.get("truncated")),
        "created_at": _at(message),
        # Which one the caller came in on.
        "is_subject": message.id == subject,
    }


# ── SSE parsing helpers ───────────────────────────────────────


def _parse_sse_line(line: str) -> tuple[str, str] | None:
    """Parse a single SSE event block (event: + data:).

    SSE lines come in pairs. For the purposes of event inspection we
    accept a relaxed shape where a single line can carry both parts
    separated by ``\\n`` (which is what FakeProxyClient emits in tests).
    """
    # FakeProxyClient emits whole events, e.g.
    # "event: chunk\ndata: {...}\n\n"
    event = None
    data = None
    for part in line.split("\n"):
        part = part.strip()
        if part.startswith("event:"):
            event = part[len("event:"):].strip()
        elif part.startswith("data:"):
            data = part[len("data:"):].strip()
    if event is None or data is None:
        return None
    return event, data


def _extract_chunk_text(data: str) -> str:
    """Pull the ``text`` field from a chunk payload, tolerant of shape."""
    try:
        obj = json.loads(data)
    except (ValueError, TypeError):
        return ""
    if isinstance(obj, dict):
        text = obj.get("text")
        if isinstance(text, str):
            return text
        # Claude proxy may nest in delta.text
        delta = obj.get("delta")
        if isinstance(delta, dict):
            inner = delta.get("text")
            if isinstance(inner, str):
                return inner
    return ""
