apiVersion: v1
kind: Service
metadata:
  name: fontem-community-api
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: fontem-community-api
  ports:
    - port: 8001
      targetPort: 8001
