"""Baseline: catch the migration history up to the models.

Everything below shipped via ``Base.metadata.create_all`` plus a dozen
hand-written ``ALTER TABLE ... ADD COLUMN IF NOT EXISTS`` statements in
the FastAPI lifespan, so none of it was ever recorded as a migration.
Measured before this revision: ``alembic upgrade head`` produced 130
columns while prod actually had 218 — 12 tables and 9 columns that no
migration created.

WHAT THIS IS FOR: making a FRESH database match the models. Applying
001..008 to an empty database now reproduces the model metadata exactly
(verified: a subsequent --autogenerate yields an empty upgrade()).

WHAT THIS IS NOT FOR: existing databases. They already have every one of
these objects, so running this against them would fail on the first
CREATE TABLE. They get ``alembic stamp 008`` instead, which records the
revision without executing any DDL — see scripts/adopt_alembic.py, which
refuses to stamp unless it has first proved the live schema already
satisfies the models.

The two ``drop_table`` calls in upgrade() are assist_conversations and
assist_messages: created by 002, replaced by ``conversations`` in the
models, and still present in the deployed databases. Because existing
environments are stamped rather than upgraded, this revision never drops
them there — those databases keep the legacy tables and the adoption
script reports them as a known divergence rather than deleting data.

Revision ID: 008
Revises: 007
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "008"
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('actor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_log_actor', 'activity_log', ['actor_id', 'created_at'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_grants',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resource_grants_lookup', 'resource_grants', ['resource_type', 'resource_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('avatar_x', sa.Float(), nullable=False),
    sa.Column('avatar_y', sa.Float(), nullable=False),
    sa.Column('show_email', sa.Boolean(), nullable=False),
    sa.Column('use_custom_email', sa.Boolean(), nullable=False),
    sa.Column('custom_email', sa.Text(), nullable=False),
    sa.Column('home_nuts', sa.Text(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('data_projects',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('investigation_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dossiers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('investigation_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investigation_members',
    sa.Column('investigation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('investigation_id', 'user_id')
    )
    op.create_table('visualizations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('widget_type', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('investigation_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_plots',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['data_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_queries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('lang', sa.Text(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['data_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('report_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_translations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('report_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lang', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'lang', name='uq_report_translation_lang')
    )
    op.drop_index(op.f('ix_assist_msg_conv_created'), table_name='assist_messages')
    op.drop_index(op.f('ix_assist_msg_user_created'), table_name='assist_messages')
    op.drop_table('assist_messages')
    op.drop_table('assist_conversations')
    op.add_column('reports', sa.Column('nuts_region', sa.Text(), nullable=False))
    op.add_column('reports', sa.Column('parent_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('reports', sa.Column('dossier_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('reports', sa.Column('investigation_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('reports', sa.Column('language', sa.Text(), nullable=False))
    op.add_column('reports', sa.Column('content_version', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reports', 'dossiers', ['dossier_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'reports', 'investigations', ['investigation_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_story_tags_tag'), table_name='story_tags')
    op.drop_index(op.f('ix_user_followed_tags_tag'), table_name='user_followed_tags')
    op.add_column('users', sa.Column('password_hash', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('locked_until', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'password_hash')
    op.create_index(op.f('ix_user_followed_tags_tag'), 'user_followed_tags', ['tag'], unique=False)
    op.create_index(op.f('ix_story_tags_tag'), 'story_tags', ['tag'], unique=False)
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'content_version')
    op.drop_column('reports', 'language')
    op.drop_column('reports', 'investigation_id')
    op.drop_column('reports', 'dossier_id')
    op.drop_column('reports', 'parent_id')
    op.drop_column('reports', 'nuts_region')
    op.create_table('assist_conversations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conversation_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('assist_conversations_pkey')),
    sa.UniqueConstraint('user_id', 'conversation_key', name=op.f('uq_assist_conv_user_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('assist_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('tokens_in', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tokens_out', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("role::text = ANY (ARRAY['user'::character varying, 'assistant'::character varying]::text[])", name=op.f('ck_assist_msg_role')),
    sa.ForeignKeyConstraint(['conversation_id'], ['assist_conversations.id'], name=op.f('assist_messages_conversation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('assist_messages_pkey'))
    )
    op.create_index(op.f('ix_assist_msg_user_created'), 'assist_messages', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_assist_msg_conv_created'), 'assist_messages', ['conversation_id', 'created_at'], unique=False)
    op.drop_table('report_translations')
    op.drop_table('conversations')
    op.drop_table('data_queries')
    op.drop_table('data_plots')
    op.drop_table('visualizations')
    op.drop_table('investigation_members')
    op.drop_table('dossiers')
    op.drop_table('data_projects')
    op.drop_table('user_profiles')
    op.drop_index('ix_resource_grants_lookup', table_name='resource_grants')
    op.drop_table('resource_grants')
    op.drop_table('investigations')
    op.drop_index('ix_activity_log_actor', table_name='activity_log')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
